### ISSUE TITLE
Export file cache invalidate - touch all files

### ISSUE THREAD

**Issue by Halama** [keboola/cli-utils#4]
Potřebujeme v jednom projektu switchnout custom S3 storage na Keboola provided S3 storage a potřebujeme aby cahované soubory které leží ve staré S3 přestaly fungovat. Zůstanou jenom jejich metadata.

To uděláme tak že se napíše skript který nastaví `keboola.touch` atribut všem tabulkám v projektu. Tím změní `lastChangeDate` tabulky které je součástí klíče cache.

**Comment by ondrejhlavacek** [comment]
Co kdyby to podporovala přímo Connection? Ale jestli to je jednorázovka, tak je to v pohodě.

**Comment by Halama** [comment]
jednorazovka

**Comment by Halama** [comment]
rovnou tam udelam at to ten atribut zas hned smaze :)
